### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by ethancohen123** [ml-jku/hti-cnn#3]
Hi,
Thanks for the subdataset !
Could you please point out where are the metadata regarding the npz files please ? I found them in form of train/test/val but is there a file with all the metadata gathered ?
Thanks

**Comment by markhofm** [comment]
Hi!
Is the metadata in the train/val/test index files insufficient or do you mean combining it into a single file?
You could combine all rows from the three files of one of the three splits to generate one file with metadata for all samples.

Best regards,
Markus

**Comment by ethancohen123** [comment]
Oh okay I was a bit confused because there is nbr1 2 and 3 so I didn't know that regrouping all from one number could actually gives the all metadata. 
So for each npz files how can one retrieve for examples the smiles associated to the images ? By linking the file name to the metadata ? 
Thanks 
Ethan

**Comment by markhofm** [comment]
The three datasplits represent different random assignments of samples to the train/val/test sets, but all three cover the full dataset. 
And yes, the column "SAMPLE_KEY" in the metadata corresponds to the name of the npz files.
Best regards,
Markus

**Comment by ethancohen123** [comment]
Okay thanks a lot for the infos

**Comment by ethancohen123** [comment]
An other question regarding the metadata, can we access the concentration ? I don't find it on the dataframe
Best 
Ethan

**Comment by gklambauer** [comment]
We havent used any concentration data. Please refer to the original cellpainting dataset in this case: https://github.com/gigascience/paper-bray2017
